# version: '3'
services:

  eureka-service:
    build: 
      context: ./eureka-service
    networks:
      - microservices-network
    ports:
      - 8761:8761
    container_name: eureka-service

  api-gateway:
    build: 
      context: ./api-gateway
    networks:
      - microservices-network
    ports:
      - 80:80
    depends_on:
      - eureka-service
    container_name: api-gateway

  application:
    build: 
      context: ./application
    depends_on:
      - eureka-service
    ports:
      - 8080:8080
    networks:
      - microservices-network
    container_name: application
    environment:
      - ENV_VALUE=${MY_ENV_VALUE}

networks:
  microservices-network: