eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
server:
  port: 8080
  servlet:
    context-path: /api/v1
  error:
    include-message: always
spring:
  application:
    name: application
  cloud:
    config:
      profile: local

key:
  something: ${ENV_VALUE}

management:
    endpoints:
        web:
            exposure:
                include: '*'