eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-service:8761/eureka
server:
    port: 8080
    servlet:
        context-path: /api/v1
spring:
    application:
        name: application
    cloud:
        config:
            profile: local