
server:
  port: 8761
spring:
  application:
    name: EUREKA-SERVICE
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    response-cache-update-interval-ms: 5000