
server:
  port: 8761
spring:
  application:
    name: EUREKA-SERVICE

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    response-cache-update-interval-ms: 5000

management:
    endpoints:
        web:
            exposure:
                include: '*'