name: Microservices Build

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Microservices
      env:
        MY_ENV_VALUE: "Github Value"
      run:  docker-compose -f "docker-compose.yml" up -d --build
